### ISSUE TITLE
Security issue in Readme

### ISSUE THREAD

**Issue by notque** [sapcc/with-kubectl-port-forward#7]
I don't think this is appropriate for a public repo. 

"Keppel has a PostgreSQL database that can be reached passwordless on localhost"

Perhaps I'm incorrect here, but I would remove this and use a different example.

**Comment by majewsky** [comment]
Why is that a concern? `localhost` here means that you need to be in the Docker container where the Postgres is running. If an attacker can get there, they already have access to the filesystem containing the database's data files, so passwordless auth to the Postgres is no privilege escalation at all.

Also, the behavior described in the README can also be plainly seen from the helm-charts.
